name: ci

on:
  push:
    branches:
      - 202*
    tags:
      - v*
  pull_request:


jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Package and Run all the Tests
        run: mvn verify
      - name: Upload Packaged App
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: |
            Dockerfile
            target/*.jar

  release:
    name: Release on Heroku
    runs-on: ubuntu-20.04
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: menu-server-production
    steps:
      - name: Login to Heroku Container Registry
        run: heroku container:login
      - name: Download jar app
        uses: actions/download-artifact@v2
        with:
          name: app-jar
      - name: Building and Pushing Image
        run: heroku container:push api
      - name: Release API
        run: heroku container:release api
